title: <p>🔥🔥🔥Simón Fonseca🔥🔥🔥</p>

logo: "images/93984.png"

description:
  <p align="center">
  <a href="">LinkedIn</a> |
  <a href="https://github.com/simon-FH">GitHub</a>
  </p>
  
  <p align="justify">
  I am student of engineering physics at Universidad de la Frontera, Chile.
  <br><br>
  I like JRPGs and chocolate ice cream.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
