title: <p>Lecturas de formación socialista</p>

logo: "images/FO00-1965.JPG"

description:
  <p align="justify">
  Un pequeño repositorio en construcción para la formación teórica de la Brigada Universitaria Socialista Santiago Faundez.
  <br><br>
  Cualquier aporte o sugerencia es más que bienvenida.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
